/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[UserName]
      ,[Email]
      ,[EmailConfirmed]
      ,[Name]
      ,[Lastname]
      ,[Grad]
      ,[Drzava]
      ,[BrojPasosa]
      ,[BrojTelefona]
      ,[TipKorisnika]
      ,[PromenioPassword]
  FROM [TravelBoisDB].[dbo].[AppUsers]