/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[User]
      ,[Kola]
	  ,[Filijala]
      ,[Renta]
      ,[Od]
      ,[Do]
	  ,[BrzaRezervacija]
  FROM [TravelBoisDB].[dbo].[Zauzetost]